[project]
name = "shockwaveparser"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "standard-aifc (>=3.13.0,<4.0.0); python_version >= '3.13'",
    "standard-sunau (>=3.13.0,<4.0.0); python_version >= '3.13'"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
