[project]
name = "shockwaveparser"
version = "0.1.0"
description = ""
requires-python = ">=3.8"
dependencies = [
    "standard-aifc (>=3.13.0,<4.0.0); python_version >= '3.13'",
    "standard-sunau (>=3.13.0,<4.0.0); python_version >= '3.13'",
    "bitstring (>=4.3.1,<5.0.0)",
    "pillow",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
